# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_wrappers.ipynb.

# %% auto 0
__all__ = ['hello']

# %% ../nbs/04_wrappers.ipynb 5
def hello():
    print(f'''
    Welcome :) \n
    You can find additional documentation here: https://k111git.github.io/ab-test-toolkit/
    ''')
    pass
